# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Spiro Generation
      run: |
        pwd
        PWD=$(pwd)
        export PYTHONPATH=$PWD
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
        python examples/Circles_in_Rings/*.py
        ls examples/Circles_in_Rings/*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: spiro-generated-files
        path: examples/Circles_in_Rings
